site: Sushi6006
title: Sushi6006
greetings: Hi 👋
description: >-
  Hey! What ya doin' at ma place?!<br/><br/>
  Mistaken or confused if you are, here is the SushiHub of the SushiCat named Sushi6006
lang: en-US
data-theme: dark  # default theme "dark" | "light"

author:
  name: Sushi6006
  bio: human. (probably) student. passionate keeb.
  userpicture: 
  username: Sushi6006
  github: Sushi6006
  twitter: Sushi6006
  email: lin.terry.x@gmail.com

# Font Settings
googlewebfonts: family=Play:wght@400;700&family=Source+Code+Pro:ital,wght@0,200;0,300;0,400;0,600;0,700;0,900;1,300;1,400;1,500;1,600;1,700;1,900

# URL settings
url: "https://sushi6006.github.io"
baseurl: ""
permalink: pretty


markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false


